command:
  - streamlit
  - run
  - app.py

env:
  - name: DATABRICKS_HOST
    value: https://adb-3666479212731434.14.azuredatabricks.net
  - name: DATABRICKS_TOKEN
    valueFrom: secret
  - name: JOB_ID
    value: "319455235888743"
  - name: PBI_CLIENT_SECRET
    valueFrom: pbisecret
  - name: TS_CLIENT_USERNAME
    valueFrom: tsusername
  - name: TS_CLIENT_PWD
    valueFrom: tspassword

resources:
  - name: default
    description: Default compute for BrickShift app
    spark_version: 13.3.x-scala2.12
    node_type_id: Standard_DS3_v2
    num_workers: 0